/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Description {
  versionMajor: number;
  versionMinor: number;
  versionPatch: number;
  moduleId: Array<number>;
  moduleIdLen: number;
  maxPcrs: number;
  lockedPcrs: Array<number>;
  lockedPcrsLen: number;
  digest: string;
}
export interface PcrDescription {
  lock: boolean;
  data: Array<number>;
}
export function open(): number;
export function init(): number;
export function close(fd: number): void;
export function exit(fd: number): void;
export function extendPcr(
  fd: number,
  index: number,
  data: Array<number>
): Array<number>;
export function getPcrDescription(fd: number, index: number): PcrDescription;
export function lockPcr(fd: number, index: number): void;
export function lockPcrs(fd: number, range: number): void;
export function getDescription(fd: number): Description;
export function getAttestationDoc(
  fd: number,
  userData: Array<number>,
  nonceData: Array<number>,
  pubKeyData: Array<number>
): Array<number>;
export function getRandom(fd: number): Array<number>;
