/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Description {
  versionMajor: number;
  versionMinor: number;
  versionPatch: number;
  moduleId: string;
  maxPcrs: number;
  lockedPcrs: Array<number>;
  digest: string;
}
export interface PcrDescription {
  lock: boolean;
  data: Buffer;
}
export function open(): number;
export function init(): number;
export function close(fd: number): void;
export function exit(fd: number): void;
export function extendPcr(fd: number, index: number, data: Buffer): Buffer;
export function getPcrDescription(fd: number, index: number): PcrDescription;
export function lockPcr(fd: number, index: number): void;
export function lockPcrs(fd: number, range: number): void;
export function getDescription(fd: number): Description;
export function getAttestationDoc(
  fd: number,
  userData?: Buffer | undefined | null,
  nonce?: Buffer | undefined | null,
  publicKey?: Buffer | undefined | null
): Buffer;
export function getRandom(fd: number): Buffer;
